name: Tag Release

on:
  push:
    tags:
      - '*.*.*' # Trigger only for SemVer tags

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Bundle
        run: ./scripts/bundle.sh ${{ github.ref_name }}

      - name: Log commits
        id: commits
        run: |
          TAG=${{ github.ref_name }}
          PREV_TAG=$(git describe --tags --abbrev=0 $TAG^ 2>/dev/null || echo "")
          if [ -z "$PREV_TAG" ]; then
            COMMITS=$(git log $TAG --pretty=format:"- %s (%h) by %cN")
          else
            COMMITS=$(git log $PREV_TAG..$TAG --pretty=format:"- %s (%h) by %cN")
          fi
          echo $COMMITS > commits.txt

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ github.ref_name }}
        run: |
          COMMIT_LOG=$(cat ./commits.txt)
          gh release create "$TAG" \
            --draft \
            --title "$TAG" \
            --notes "## Changes\n\n$COMMIT_LOG" \
            module.zip \
            dist/module.json
